import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SWRegistration from './SWRegistration';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className=" min-h-screen pb-18 min-h-full flex flex-col">
        
        {children}
        
        <header className="fixed bottom-0 left-0 w-full z-50 bg-gray-800/90 backdrop-blur-md shadow-lg border-b border-gray-700">
  <nav className="max-w-6xl mx-auto flex items-center justify-between p-4">
    <div className="flex gap-4">
      <Link href="/"
        className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg transition"
      >
        Calculadora
      </Link>

      <Link href="/notas"
        className="bg-green-600 hover:bg-green-700 px-4 py-2 rounded-lg transition"
      >
        Notas
      </Link>
    </div>
  </nav>
</header>

      <SWRegistration />
      </body>
    </html>
  );
}
